FROM eclipse-temurin:17-jdk
WORKDIR /app

# gradle 및 설정 복사
COPY gradlew .
COPY gradle gradle
COPY build.gradle .
RUN chmod +x ./gradlew

# 의존성 다운로드 (BuildKit 캐시 활용)
RUN --mount=type=cache,target=/root/.gradle ./gradlew dependencies

# 소스 코드 복사 및 빌드
COPY src src
RUN --mount=type=cache,target=/root/.gradle ./gradlew build -x test -x asciidoctor

# 빌드된 jar 파일을 고정된 이름으로 복사
RUN cp build/libs/*.jar app.jar

# 실행 환경 설정
ENTRYPOINT ["java", "-jar", "app.jar"]